trigger:
  branches:
    include:
      - main  # Set the branch to trigger builds

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image to use

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Specify the Node.js version to use
    displayName: 'Install Node.js'

  - script: npm install  # Install dependencies
    displayName: 'Install Dependencies'

  - script: npm test  # Run tests
    displayName: 'Run Tests'

  - script: npm run build  # Build the application
    displayName: 'Build Application'

  - script: echo "Build completed successfully!"  # Confirmation message
    displayName: 'Confirmation Message'
